services:
  web:
    image: ghcr.io/k-t-corp/ward:master
    ports:
      - "4444:4444"
    restart: always
    privileged: true
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /stats
    volumes:
      - /home/mastodon/ward/setup.ini:/setup.ini
